### ISSUE TITLE
compatibility with leiningen 2.9.0

### ISSUE THREAD

**Issue by minhtuannguyen** [venantius/ultra#103]
Using ultra(0.5.4) in combination with the  leiningen version 2.9.0, I get the following exception:

```
    Caused by: java.lang.RuntimeException: Unable to resolve var: clojure.instant/thread-local-utc-date-format in this context
    ....
    fipp.visit$eval3333$loading__6706__auto____3334.invoke (visit.cljc:1)
    fipp.visit$eval3333.invokeStatic (visit.cljc:1)
    fipp.visit$eval3333.invoke (visit.cljc:1)
    ...
    puget.printer$eval2467$loading__6706__auto____2468.invoke (printer.clj:1)
    ...
    whidbey.repl$eval2418$loading__6706__auto____2419.invoke (repl.clj:1)
    .....
    ultra.colorscheme$eval1974$loading__6706__auto____1975.invoke (colorscheme.clj:1)
```

apparently fipp doesn't work well with the new leningen version. Do you have any idea to fix it? Thank you

**Comment by venantius** [comment]
Given this is an upstream issue I'd recommend filing an issue in that repository.

**Comment by minhtuannguyen** [comment]
ok, thank you. I see that someone mentions this [issue](https://github.com/brandonbloom/fipp/issues/60) already

**Comment by cichli** [comment]
I left a [comment](https://github.com/brandonbloom/fipp/issues/60#issuecomment-470468952) on the fipp issue with some more detail, but in short you can set the environment variable `LEIN_USE_BOOTCLASSPATH` to `no` to work around this.

**Comment by minhtuannguyen** [comment]
Thank you for your hint!
