### ISSUE TITLE
Upgrade Whidbey and Puget

### ISSUE THREAD

**Issue by greglook** [venantius/ultra#25]
@venantius I released a new version of Whidbey with the `:escape-types` changes, which fixes #17.

I also moved the tag extension for byte arrays and URI values over from Puget. See [this merge commit](https://github.com/greglook/whidbey/commit/4f805cd03cdabb7cb8a7b41f4682820eb5d9d919) for the relevant changes.

**Comment by venantius** [comment]
Great, pinning this to the 0.3.3 milestone to be released next Monday.

**Comment by venantius** [comment]
Pushing this to Ultra `0.3.4`

**Comment by venantius** [comment]
#31 should address this.
