### ISSUE TITLE
Leiningen/REPLy version dependency

### ISSUE THREAD

**Issue by mtkp** [venantius/ultra#3]
I wasn't getting colorized output after adding Ultra to my profile. Turns out it was because I was using Lein 2.3, but I didn't know this was the issue until coming across [Whidbey](https://github.com/greglook/whidbey)'s docs.

Might be worth specifying in Ultra's readme that Whidbey has the following requirement:

> The easiest way to use Whidbey is as a Leiningen plugin. Note that this requires Leiningen version 2.4.2 or higher for functionality in REPLy 0.3.1.

**Comment by venantius** [comment]
Updated the README, thanks for the heads up!
