### ISSUE TITLE
Error: Unable to resolve symbol: some? in this context, compiling:(io/aviso/columns.clj:189:11)`

### ISSUE THREAD

**Issue by vothane** [venantius/ultra#41]
running Ubuntu with zsh shell using Leiningen 2.5.2 on Java 1.7.0_79 OpenJDK 64-Bit Server VM I get the following error

`Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: some? in this context, compiling:(io/aviso/columns.clj:189:11)`

**Comment by venantius** [comment]
Same issue as https://github.com/venantius/ultra/issues/35.
