### ISSUE TITLE
Could not locate fipp/engine__init.class

### ISSUE THREAD

**Issue by dariooddenino** [venantius/ultra#45]
Hi! 
I've followed the getting started procedure and I'm meeting all the requirements.
If I try to launch `lein ring server` on o a project, I get this exception (I wasn't getting it before trying ultra):

`Exception in thread "main" java.io.FileNotFoundException: Could not locate fipp/engine__init.class or fipp/engine.clj on classpath: , compiling:(puget/printer.clj:1:1)`

**Comment by venantius** [comment]
What Clojure version is your project?

**Comment by dariooddenino** [comment]
This is embarrassing... I checked everything but that :( It was 1.6.0
Sorry for wasting your time and thanks!

**Comment by venantius** [comment]
No worries! It tripped me up at least once in development so I was actually expecting someone to file an issue pretty promptly after release.
