### ISSUE TITLE
Friendlier README Regarding Plugin Integration

### ISSUE THREAD

**Issue by erez-rabih** [venantius/ultra#48]
Hi,

Thanks for the great lein plugin, it is extremely useful.

When I tried installing it I followed the readme and added
```clojure
{:user {:plugins [[venantius/ultra "0.4.0"]]}}
```
But couldn't see any colors in the REPL. It took me a while to figure out the default color scheme has no colors and I have to set the color scheme with:
```clojure
:ultra {:color-scheme :solarized_dark}
```
Did I miss the documentation regarding it? Maybe it is worth stating in a more visible place so others won't have the same problem.

**Comment by venantius** [comment]
This is actually a bug, not a README fix. My guess is this was introduced in `0.4.0` when the interface to Whidbey changed. There should be a default colorscheme set. 

At this point frankly I think I'd like to do away with color-schemes as a customization and just force a single default - nobody so far has given me any indication that they're altering the colorscheme at all and in fact what I call "solarized dark" really just adapts to whatever terminal settings they have.

**Comment by olivergg** [comment]
@erez-rabih Where did you put the `:ultra {:color-scheme :solarized_dark}` line ? I'm trying to have a colorized REPL when running `lein repl` in a terminal, but I don't know where to put this configuration map in  ~/.lein/profiles.clj file

**Comment by erez-rabih** [comment]
@olivergg This is the contents of my ~/.lein/profiles.clj:
```clojure
{:user {:plugins [[venantius/ultra "0.4.0"]]
        :ultra {:color-scheme :solarized_dark}
        }}
```

**Comment by olivergg** [comment]
@erez-rabih  Thanks ;)
