### ISSUE TITLE
Color scheme not working

### ISSUE THREAD

**Issue by anthoq88** [venantius/ultra#49]
Hello,

I'm probably doing something here.
I can't seem to get the repls colour scheme working.

Here is my ~/.lein/profiles.clj
`{:user {:plugins [[venantius/ultra "0.4.0"]]}}`

The stack trace output formatting is working so it looks like the plugin is being applied.

<img width="1265" alt="screen shot 2015-12-25 at 12 29 03 pm" src="https://cloud.githubusercontent.com/assets/1674432/11998809/4025cd8c-ab03-11e5-8bc8-6a1f5208b66d.png">

Using terminal.app on Mac osx

**Comment by venantius** [comment]
Ultra doesn't overwrite the `print` function - it sets the REPL to print syntax-highlighted response values. What happens if you just type `{:a 1}` at the REPL?

**Comment by anthoq88** [comment]
Still unhighlighted :(

<img width="598" alt="screen shot 2015-12-25 at 1 27 59 pm" src="https://cloud.githubusercontent.com/assets/1674432/11999149/6a647636-ab0b-11e5-9d77-a88417db62c3.png">

**Comment by venantius** [comment]
Hmm, now that is weird. Assuming you're inside a particular project, could you do `lein deps :tree` and let me know what the output is?

If the rest of the plugin is working, you should still be able to call the colorized printer manually. What happens when you execute the following code at the REPL (you shouldn't need to do a `require`, Ultra should handle that for you):
`(ultra.printer/cprint {:a 1})`

**Comment by anthoq88** [comment]
Sure thing

`lein deps :tree`
```
➜  hello-world  lein deps :tree
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.10" :exclusions [org.clojure/clojure]]
 overrides
[venantius/ultra "0.4.0"] -> [org.clojure/tools.nrepl "0.2.11"]

Consider using these exclusions:
[venantius/ultra "0.4.0" :exclusions [org.clojure/tools.nrepl]]

 [clojure-complete "0.2.3" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/tools.nrepl "0.2.10" :exclusions [[org.clojure/clojure]]]
 [venantius/ultra "0.4.0"]
   [im.chit/hara.class "2.2.11"]
     [im.chit/hara.class.checks "2.2.11"]
     [im.chit/hara.class.inheritance "2.2.11"]
     [im.chit/hara.namespace.import "2.2.11"]
   [im.chit/hara.reflect "2.2.11"]
     [im.chit/hara.common.checks "2.2.11"]
     [im.chit/hara.common.string "2.2.11"]
     [im.chit/hara.common "2.2.11"]
       [im.chit/hara.common.error "2.2.11"]
       [im.chit/hara.common.hash "2.2.11"]
       [im.chit/hara.common.primitives "2.2.11"]
     [im.chit/hara.data.map "2.2.11"]
     [im.chit/hara.protocol.string "2.2.11"]
   [io.aviso/pretty "0.1.18"]
   [mvxcvi/puget "0.9.2"]
     [fipp "0.6.2"]
       [org.clojure/core.rrb-vector "0.0.11"]
     [mvxcvi/arrangement "1.0.0"]
   [mvxcvi/whidbey "1.1.1"]
     [org.clojure/data.codec "0.1.0"]
   [org.clojars.brenton/google-diff-match-patch "0.1"]
   [robert/hooke "1.3.0"]
   [venantius/glow "0.1.2"]
     [clj-antlr "0.2.2"]
       [org.antlr/antlr4-runtime "4.2.2"]
         [org.abego.treelayout/org.abego.treelayout.core "1.0.1"]
         [org.antlr/antlr4-annotations "4.2.2"]
       [org.antlr/antlr4 "4.2.2"]
         [org.antlr/ST4 "4.0.8"]
         [org.antlr/antlr-runtime "3.5.2"]
     [instaparse "1.4.1"]
```



`(ultra.printer/cprint {:a 1})`
![screen shot 2015-12-25 at 1 46 52 pm](https://cloud.githubusercontent.com/assets/1674432/11999246/193acdac-ab0e-11e5-86d8-8771ae7af6fe.png)

**Comment by venantius** [comment]
The cprint output suggests to me that this is simply a matter of Terminal configuration rather than an Ultra issue. Could you show me what your Terminal.app's "Profiles" window looks like (in Preferences)?

**Comment by anthoq88** [comment]
Yeah I had that thought - but I couldn't find a setting that would cause this issue.

![screen shot 2015-12-28 at 6 48 05 am](https://cloud.githubusercontent.com/assets/1674432/12011752/37951582-ad2f-11e5-9a03-e92317d486d1.png)
![screen shot 2015-12-28 at 6 48 11 am](https://cloud.githubusercontent.com/assets/1674432/12011753/379beda8-ad2f-11e5-91ad-53ad9bfab0c0.png)

**Comment by anthoq88** [comment]
I'm using zsh if that means anything

**Comment by venantius** [comment]
I suspect zsh may be the issue here; some quick Googling suggests that zsh has its own escape codes for colors and that traditional ANSI escape codes for coloring may not work. If that's true, then the fix *should* be relatively simple - just shell out to the console to figure out what shell Leiningen is being executed under and configure escape codes as necessary.

**Comment by bradJM** [comment]
For what it's worth, I was able to get highlighting working in zsh by adding :color-scheme to my profiles.clj explicitly as described in #48. Might be worth a shot!

**Comment by venantius** [comment]
Oh balls. I should really fix that bug :/

**Comment by bradJM** [comment]
I wrote a small patch this morning that seems to fix it, if you'd like a PR. It's nothing fancy, it replaces the nils in the default color scheme with the values from Solarized Dark. It would close a few issues while you decide whether to continue supporting custom color schemes though. :)

**Comment by venantius** [comment]
Sure, why not? Can't hurt to look at it, at the very least :)

**Comment by bradJM** [comment]
Cool, I've opened #51. Thanks for having a look!
