### ISSUE TITLE
stacktraces are empty

### ISSUE THREAD

**Issue by tcrayford** [venantius/ultra#5]
if I go to a new repl and try out expressions that throw exceptions, stacktraces come out empty:

http://cl.ly/image/081V1o3X2b11

**Comment by venantius** [comment]
Hmm, I thought I had fixed this a while back. I'll take a closer look at this tonight.

**Comment by rafadc** [comment]
As a workaround you can do 
```
(pst)
```
after the stacktrace and it will be shown in the nice ultra format.

**Comment by tcrayford** [comment]
@venantius : did you look at this yet?

**Comment by tcrayford** [comment]
btw, I checked, and `clojure.repl/pst` is definitely bound to aviso's pretty print:

```clojure
clojure.repl/pst
#<io.aviso.repl$pretty_pst@20bf2e8 io.aviso.repl$pretty_pst@20bf2e8>
```

and even calling `(clojure.repl/pst (ex-info "" {}))` gives a stacktrace, so this is really quite odd.

**Comment by tcrayford** [comment]
@venantius : if you have any pointers, I'm happy going and looking

**Comment by venantius** [comment]
Yeah, sorry, haven't had a chance to check it out, but haven't forgotten. Busy week. 

If you want to go digging, I'm sure the answer is in the disparity between `ultra.repl` and `ultra.stacktrace`; shouldn't be hard to toy with it a bit and achieve the desired behavior.

**Comment by tcrayford** [comment]
yeah, got it, the docs for `io.aviso.repl/pretty-repl-caught`:

```
  "A replacement for `clojure.main/repl-caught` that prints the exception to `*err*`, without a stack trace or properties."
```

Think we just need to swap that out to be `pretty-pst` as per the comment in `ultra.repl`
