### ISSUE TITLE
io.aviso/pretty 0.1.23

### ISSUE THREAD

**Issue by hlship** [venantius/ultra#53]
Pretty has evolve a bit since the 0.1.18 release; some people trying to use newer version of pretty inside utlra are hitting issues.

It would be valuable for ultra to update to the latest version of pretty.

I may be able to provide a PR later in the week.

**Comment by hlship** [comment]
People keep getting a missing namespace, since io.aviso.nrepl was removed; pretty does a smarter job of injecting pretty exception reporting at startup now.

**Comment by venantius** [comment]
A PR would be awesome, yeah! If you're not able to come up with something let me know.

**Comment by venantius** [comment]
Should be resolved as of https://github.com/venantius/ultra/commit/ec5d6037d9f72dd1ea763833c9bb5f8dab37b56d
