### ISSUE TITLE
Coloring not working

### ISSUE THREAD

**Issue by freckletonj** [venantius/ultra#55]
I'm on ubuntu 14.04, Clojure v 1.7.0, my ~/.lein/profiles.clj looks like this:

`{:user {:plugins [[venantius/ultra "0.4.0"]]}}`

and when I run `lein repl` I see no colors, however I do see formatting of the text's spacing.

I notice all the screenshots are on macs, I assume this is compatible with linux, any idea what I'm doing wrong?

**Comment by venantius** [comment]
I believe this problem is fixed on master, just not yet on the most recent version. Could you try downloading master, running `lein install` and verifying that the problem is resolved?

**Comment by freckletonj** [comment]
huh. it works. Thank you for that! I'm a little confused though, could you explain what I just did, where did it install to, and how does that install overwrite my `profiles.clj`? What's going on?

**Comment by venantius** [comment]
It installed to the same place things are normally installed to. The difference is that what's currently on master clobbers the version that you grabbed from Clojars - I can't update what's on Clojars once the release has happened, so this bug be officially resolved with the `0.4.1` release.

**Comment by venantius** [comment]
(Things are normally installed to `~/.m2/repository/`)

**Comment by freckletonj** [comment]
You rock, thanks so much!
