### ISSUE TITLE
Colorization is not enabled (clojure 1.8, leiningen, ultra '0.4.0')

### ISSUE THREAD

**Issue by altV** [venantius/ultra#56]
Hello! Can you plz advise how to enable colorization and what could be the reason?

lein profiles contains only ultra plugin

**Comment by venantius** [comment]
See #55 and #49. This is resolved on master, just tweaking some final things for version `0.4.1`

**Comment by altV** [comment]
thank you!

**Comment by venantius** [comment]
Marking as resolved. Version 0.4.1 should do the trick for you.
