### ISSUE TITLE
v0.4.1 Possibly confusing dependencies found

### ISSUE THREAD

**Issue by madvas** [venantius/ultra#60]
When I try to include ultra as: 

```
[venantius/ultra "0.4.1" :exclusions [org.clojure/clojure
                                      hiccup]]
```

I still get error like 

```
Possibly confusing dependencies found:
[org.clojure/clojure "1.7.0" :exclusions [clj-http com.stuartsierra/component]]
 overrides
[venantius/ultra "0.4.1"] -> [org.clojure/clojure "1.8.0"]

Consider using these exclusions:
[venantius/ultra "0.4.1" :exclusions [org.clojure/clojure]]

[endophile "0.1.2" :exclusions [clj-http com.stuartsierra/component]] -> [hiccup "1.0.3"]
 overrides
[venantius/ultra "0.4.1"] -> [venantius/glow "0.1.3"] -> [hiccup "1.0.5"]

Consider using these exclusions:
[venantius/ultra "0.4.1" :exclusions [hiccup]]

Aborting due to :pedantic? :abort

```

As if it completely ignored `:exclusions`.
Interestingly, when I include version `0.4.0` as `[venantius/ultra "0.4.0"]` I don't even have to put anything into `:exclusions` and everything works

**Comment by venantius** [comment]
Hm. I'm not totally sure what's going on here but I'd guess the fact that Ultra the plugin injects itself as a dependency is what's causing the root issue here. 

Fwiw, Ultra 0.5.0 will drop the dependency on Hiccup. I hadn't really considered the implications of dropping the Clojure dependency itself, though I don't suppose there's anything intrinsically wrong with it.

**Comment by venantius** [comment]
I believe https://github.com/venantius/ultra/commit/5d0c3cb857e37b28e40a51b1bae8d2ddfd242c96 should help to resolve this. When you get a chance, please download Ultra `0.5.1` and see if this issue has persisted.

**Comment by venantius** [comment]
Closing due to lack of response.
