### ISSUE TITLE
Ultra not compatible with Clojure >= alpha11

### ISSUE THREAD

**Issue by arichiardi** [venantius/ultra#62]
Hello @venantius,

I just wanted to report that it seems like `ultra` `0.4.1` includes a version of `hara` which [does not conform the new spec](https://github.com/zcaudate/hara/issues/26) and therefore fails with `clojure` >= `alpha11`.

I have noticed that you don't include it anymore in the new SNAPSHOT so I will wait of a new release but I decided to open this a a reminder :dancers:

**Comment by venantius** [comment]
The 0.5.0 release will be going out shortly which should resolve this.

**Comment by arichiardi** [comment]
Thanks!
