### ISSUE TITLE
Ultra throws "= expects more than one argument" while this is allowed

### ISSUE THREAD

**Issue by FreekPaans** [venantius/ultra#72]
When ultra is loaded
```clj
(is (= 1))
```
throws an Exception "= expects more than one argument", but this is actually valid, so I guess it should work in ultra as well?

**Comment by venantius** [comment]
Sorry, can you elaborate on what you mean by "when ultra is loaded"?

**Comment by FreekPaans** [comment]
Ah, I mean that ultra is enabled, that is enhancing test output and all.

**Comment by venantius** [comment]
Hm, right you are. I'll have to look into this.

**Comment by venantius** [comment]
I am going to close this as "won't fix". 

While you're correct that Clojure legally permits `=` to take a single arity, it will always return true. In that context I cannot see a valid reason for using it within an `is` testing block. 

It's possible that I'm missing something, in which case I'm happy to revisit this. But the current behavior seems reasonable to me, and likely to help people from accidentally writing tests in which they intended to compare two or more objects but failed to align parentheses correctly.
