### ISSUE TITLE
Is clojure 1.9 supported yet?

### ISSUE THREAD

**Issue by matanster** [venantius/ultra#89]
Is clojure 1.9 supported yet?
Thanks!!

And thanks for this plugin!

**Comment by venantius** [comment]
Hi - it should be. Please let me know if you have any issues.

**Comment by venantius** [comment]
That should work, yes. Can you provide a re-producible example (i.e. small project and steps to reproduce)?

**Comment by didibus** [comment]
Same thing happens to me, I'll see if I can repro.

**Comment by yytsui** [comment]
Include these two lines in the project's `project.clj`
` :middleware [ultra.plugin/middleware]`
`:plugins [[venantius/ultra "0.5.2"]]`

then run

`%lein repl`

I got error messages:

> [WARNING] No nREPL middleware descriptor in metadata of #'clojure.tools.nrepl.middleware.render-values/render-values, see nrepl.middleware/set-descriptor!
> [WARNING] No nREPL middleware descriptor in metadata of #'clojure.tools.nrepl.middleware.render-values/render-values, see nrepl.middleware/set-descriptor!
> nREPL server started on port 61710 on host 127.0.0.1 - nrepl://127.0.0.1:61710
> ERROR: Unhandled REPL handler exception processing message {:id a370c61d-9bf8-45d5-8a23-41559e3096c3, :op clone}
> java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.middleware.render_values$wrap_renderer$reify__1992
> 	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
> 	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
> 	at nrepl.transport$eval339$fn__340$G__330__347.invoke(transport.clj:16)
> 	at nrepl.middleware.session$register_session.invokeStatic(session.clj:149)
> 	at nrepl.middleware.session$register_session.invoke(session.clj:142)
> 	at nrepl.middleware.session$session$fn__1039.invoke(session.clj:193)
> 	at nrepl.middleware$wrap_conj_descriptor$fn__608.invoke(middleware.clj:17)
> 	at nrepl.middleware.load_file$wrap_load_file$fn__974.invoke(load_file.clj:79)
> 	at nrepl.middleware$wrap_conj_descriptor$fn__608.invoke(middleware.clj:17)
> 	at clojure.tools.nrepl.middleware.render_values$render_values$fn__2000.invoke(render_values.clj:42)
> 	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1809.invoke(middleware.clj:22)
> 	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
> 	at nrepl.server$handle_STAR_.invoke(server.clj:15)
> 	at nrepl.server$handle$fn__1076.invoke(server.clj:27)
> 	at clojure.core$binding_conveyor_fn$fn__5297.invoke(core.clj:2027)
> 	at clojure.lang.AFn.call(AFn.java:18)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 
> 

My environment:

> nREPL server started on port 60366 on host 127.0.0.1 - nrepl://127.0.0.1:60366
> REPL-y 0.4.3, nREPL 0.5.3
> Clojure 1.9.0-alpha17
> Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11
>     Docs: (doc function-name-here)
>           (find-doc "part-of-name-here")
>   Source: (source function-name-here)
>  Javadoc: (javadoc java-object-or-class-here)
>     Exit: Control+D or (exit) or (quit)
>  Results: Stored in vars *1, *2, *3, an exception in *e

on MacOS 10.13.6.
