### ISSUE TITLE
Update org.clojure/tools.nrepl 0.2.12 to nrepl 0.5.3?

### ISSUE THREAD

**Issue by rux** [venantius/ultra#95]
According to https://github.com/clojure/tools.nrepl, the active development of nREPL has moved to https://github.com/nrepl/nrepl earlier in 2018.

**Comment by cbcoutinho** [comment]
Possibly related technomancy/leiningen#2497 and technomancy/leiningen#2506

**Comment by bbatsov** [comment]
Yes, the old project is no more. Refer to https://metaredux.com/posts/2018/10/29/nrepl-redux.html for more details. All projects should adopt the new package, as the main tooling already switched to it and tools like CIDER will just drop support for the old package very soon.

That's a simply way of supporting both versions https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl.clj#L11

**Comment by bbatsov** [comment]
@cbcoutinho Those bugs you refer to (which are the same bug actually) are unrelated to the need for updating the nREPL dep for ultra and similar packages.

**Comment by venantius** [comment]
We'll need https://github.com/greglook/whidbey/issues/26 to go in first as otherwise Ultra will be on nREPL and our deps will be on clojure.tools.nrepl.

**Comment by narkisr** [comment]
Is this issue resolved yet?

Thanks
